In [1]:
#task14
import torch
import torch.nn as nn

# Sample Input
X = torch.randn(5)

# Custom Swish Activation
class Swish(nn.Module):

    def forward(self, x):
        return x * torch.sigmoid(x)

# Create Swish Layer
swish = Swish()

# Apply Swish
swish_output = swish(X)

# Compare with ReLU
relu = nn.ReLU()
relu_output = relu(X)

print("Input:")
print(X)

print("\nSwish Output:")
print(swish_output)

print("\nReLU Output:")
print(relu_output)

Input:
tensor([ 1.2970,  0.5684, -0.7635, -1.7000, -0.2061])

Swish Output:
tensor([ 1.0185,  0.3629, -0.2427, -0.2626, -0.0925])

ReLU Output:
tensor([1.2970, 0.5684, 0.0000, 0.0000, 0.0000])
