In [11]:
#task3
import numpy as np

In [12]:
# Input Image (1 Channel, 4x4)
X = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

In [13]:
# 2x2 Filter
kernel = np.array([[1,0],
                   [0,1]])


In [14]:
# im2col Function
def im2col(image, k):
    rows = []

    for i in range(image.shape[0]-k+1):
        for j in range(image.shape[1]-k+1):

            patch = image[i:i+k, j:j+k]
            rows.append(patch.flatten())

    return np.array(rows)


In [15]:
# Convert Image into Columns
image_col = im2col(X,2)

# Convert Kernel into Column
kernel_col = kernel.flatten()

# Matrix Multiplication
output = np.dot(image_col, kernel_col)

# Output Size
output = output.reshape(3,3)

In [16]:
print("Input Image")
print(X)

print("\nKernel")
print(kernel)

print("\nim2col Matrix")
print(image_col)

print("\nConvolution Output")
print(output)

Input Image
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Kernel
[[1 0]
 [0 1]]

im2col Matrix
[[ 1  2  5  6]
 [ 2  3  6  7]
 [ 3  4  7  8]
 [ 5  6  9 10]
 [ 6  7 10 11]
 [ 7  8 11 12]
 [ 9 10 13 14]
 [10 11 14 15]
 [11 12 15 16]]

Convolution Output
[[ 7  9 11]
 [15 17 19]
 [23 25 27]]
